version: '2.1'

services:
  portunus_api:
    build: .
    environment:
      FLASK_APP: wgpt.py
      DATABASE_URL: "mysql+pymysql://wgpt:wgptpassword@db/wgpt"
      TCP_WAIT: "db 3306"
      SKIP_CREATE_DB: 0
      CERT_SSL_CA: "/certs/ca-cert.pem"
      CERT_SSL_CA_KEY: "/certs/ca-key.pem"
      CERT_SSL_SERVER: "/certs/server-cert.pem"
      CERT_SSL_SERVER_KEY: "/certs/server-key.pem"
      CERT_SSL_CHAIN: "/certs/chain-cert.pem"
    depends_on:
      - db
    volumes:
      - ./config.py:/wgpt/config.py
      - certs:/certs
    command: ["/wgpt/certgen-entrypoint.sh"]


  webserver:
    build: ./webserver
    environment:
      CERT_SSL_CA: "/certs/ca-cert.pem"
      CERT_SSL_SERVER_KEY: "/certs/server-key.pem"
      CERT_SSL_CHAIN: "/certs/chain-cert.pem"
# HTTP_USER and HTTP_PASSWORD are optional, if left blank access will be open
      HTTP_USER: "admin"
      HTTP_PASSWORD: "password"
    ports:
      - "1443:443"
    depends_on:
      - portunus_api
    volumes:
      - ./webserver/nginx.conf:/nginx.conf
      - certs:/certs


  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: wgpt
      MYSQL_PASSWORD: wgptpassword
      MYSQL_DATABASE: wgpt
    ports:
      - "43306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data:
    certs:

